defaults:
  - scope:
      path: ""
    values:
      layout: "default"
description: "Sarah Ransohoff's artwork, illustrations, cartoons, and software endeavors."
collections:
  artwork:
    output: true
url: https://sarahransohoff.com
plugins:
  - jekyll-seo-tag
