defaults:
  - scope:
      path: ""
    values:
      layout: "default"
description: "Sarah Ransohoff's artwork, cartoons, illustrations and programming projects. See her latest work and contact for commissions."
collections:
  artwork:
    output: true
url: https://sarahransohoff.com
